#!/usr/bin/bash

# This is a shell script created to push from the local repo to the remote repo (aka GitHub repo)
# easier from the 'feature' branch

# Merge both side
git checkout feature
git merge main feature
git checkout main
git merge feature main
git push; git push origin feature
